version: '3'

services:
  webapp: 
    container_name: aurafarma_app
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - database
  database:
    container_name: aurafarma_db
    image: mongo
    restart: always
    build: .
    ports:
      - "27019:27017"