services:
  webapp:
    container_name: aurafarma_app
    restart: always
    build: .
    environment:
      MONGO_URI: mongodb://database:27017/aurafarma_db
    ports:
      - "5000:3000"
    depends_on:
      - database

  database:
    container_name: aurafarma_db
    image: mongo
    restart: always
    ports:
      - "27019:27017"
